// GENERATED by scripts/scan-assets.mjs — do not edit by hand.
// Run `npm run scan` after adding or removing files in public/.

export type AssetKind = 'image' | 'video' | 'audio' | 'font' | 'data' | 'other';

export type Asset = {
	/** Path relative to public/, as passed to staticFile(). */
	path: string;
	kind: AssetKind;
	extension: string;
	bytes: number;
	/** Present for images whose header could be parsed. */
	width?: number;
	height?: number;
};

export const assets = {} as const satisfies Record<string, Asset>;

export type AssetId = keyof typeof assets;

/** Widened view of the manifest, for lookups by a runtime string. */
export const assetTable: Record<string, Asset> = assets;

export const allAssets: readonly (Asset & {id: AssetId})[] = Object.entries(
	assetTable,
).map(([id, asset]) => ({...asset, id: id as AssetId}));

export const assetsByKind = (kind: AssetKind) =>
	allAssets.filter((asset) => asset.kind === kind);
